### ISSUE TITLE
Windows: Had to change name of ccurl.dll

### ISSUE THREAD

**Issue by dnalneh** [thedewpoint/iota-basic#2]
Hi,

nice work! 

I had to change the name of the file
\node_modules\iota-basic\binaries\win32\ccurl.dll
to the name
\node_modules\iota-basic\binaries\win32\libccurl.dll
because of following error, when sending transactions:
"Error: Dynamic Linking Error: Win32 error 126" 
issued from \node_modules\ffi\lib\dynamic_library.js:75
(this error means that the file could not be found)

**Comment by thedewpoint** [comment]
Sorry about that. Windows is the only platform I haven't had a chance to test on yet since I don't have it available.  I will make this change tonight, thank you for posting it

**Comment by thedewpoint** [comment]
closing with commit https://github.com/thedewpoint/iota-basic/commit/bf21f71cc96af6a7d2cd53a0f28abd68f24e3f53

**Comment by thedewpoint** [comment]
make sure to use 1.0.3 now
